#!/usr/bin/env python3
# -------------------------------------------------
# Script Name:   Media Compressor
# Language:      Python 3
# Description:   Compress a video to a target file size using 2-pass ffmpeg encoding
# Usage:         python media_compressor.py <input_file> <target_size_in_mb>
# Depends:       ffmpeg, ffprobe (must be on PATH)
# -------------------------------------------------

import sys
import subprocess
import json
import os
from pathlib import Path

def get_video_duration(input_path: Path) -> float:
    """Uses ffprobe to extract the exact duration of the video in seconds."""
    cmd = [
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "json", str(input_path)
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        data = json.loads(result.stdout)
        return float(data["format"]["duration"])
    except (subprocess.CalledProcessError, KeyError, ValueError) as e:
        print(f"[-] Error probing file metadata with ffprobe: {e}")
        sys.exit(1)

def compress_video(input_path: Path, target_size_mb: float, output_path: Path = None):
    """Compresses video to target size using a calculated 2-pass encoding approach."""
    if not input_path.exists():
        print(f"[-] Input file not found: {input_path}")
        return

    if not output_path:
        output_path = input_path.parent / f"{input_path.stem}_compressed{input_path.suffix}"

    print(f"[*] Analyzing '{input_path.name}'...")
    duration = get_video_duration(input_path)
    print(f"[*] Video duration: {duration:.2f} seconds")

    # --- Bitrate Math Logic ---
    # Target size converted to total bits (subtracting a 5% buffer overhead safety margin)
    target_total_bits = (target_size_mb * 1024 * 1024 * 8) * 0.95
    audio_bitrate_bps = 128000  # Default safe audio allocation (128 kbps)

    # Total bitrate = bits / seconds
    total_bitrate_bps = target_total_bits / duration
    video_bitrate_bps = total_bitrate_bps - audio_bitrate_bps

    # Safety sanity checks
    if video_bitrate_bps < 100000:  # Below 100 kbps will look like absolute mush
        print("[-] Warning: Target size is too small for this video length. Output quality will suffer heavily.")
        video_bitrate_bps = 100000

    video_bitrate_kbps = int(video_bitrate_bps / 1000)
    audio_bitrate_kbps = int(audio_bitrate_bps / 1000)

    print(f"[*] Target calculated: Video {video_bitrate_kbps} kbps | Audio {audio_bitrate_kbps} kbps")

    # Handle OS specific null device for the first pass architecture
    null_device = "NUL" if os.name == "nt" else "/dev/null"

    # --- Pass 1 ---
    print("[*] Launching Pass 1/2 (Analyzing frame vectors)...")
    pass1_cmd = [
        "ffmpeg", "-y", "-i", str(input_path),
        "-c:v", "libx264", "-b:v", f"{video_bitrate_kbps}k",
        "-pass", "1", "-an", "-f", "mp4", null_device
    ]
    subprocess.run(pass1_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.WARNING)

    # --- Pass 2 ---
    print("[*] Launching Pass 2/2 (Finalizing compression)...")
    pass2_cmd = [
        "ffmpeg", "-y", "-i", str(input_path),
        "-c:v", "libx264", "-b:v", f"{video_bitrate_kbps}k",
        "-pass", "2", "-c:a", "aac", "-b:a", f"{audio_bitrate_kbps}k",
        str(output_path)
    ]
    subprocess.run(pass2_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.WARNING)

    # Clean up log files generated by the 2-pass encoder execution
    for log_file in Path(".").glob("ffmpeg2pass-0.*"):
        try:
            log_file.unlink()
        except FileNotFoundError:
            pass

    if output_path.exists():
        final_size = output_path.stat().st_size / (1024 * 1024)
        print(f"[+] Done! Saved to: {output_path.name} ({final_size:.2f} MB)")
    else:
        print("[-] Error: Compression failed to generate final output asset.")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python media_compressor.py <input_file> <target_size_in_mb>")
        print("Example: python media_compressor.py gameplay.mp4 25")
        sys.exit(1)

    file_arg = Path(sys.argv[1])
    try:
        size_arg = float(sys.argv[2])
    except ValueError:
        print("[-] Error: Target size must be a number representing Megabytes.")
        sys.exit(1)

    compress_video(file_arg, size_arg)
